#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/opt/VS-Code-Insiders/code-insiders" "/home/phinixprono1234/.config/Code - Insiders/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode-insiders://github.copilot-chat" "" "$@"